### PR TITLE
MidiLooper: Remove demo check and label

### PR DESCRIPTION
**Pull request by loowps**
I suppose the demo version label is redundant now.

### CODE REVIEW

**Review by sleiner — CHANGES_REQUESTED** [review]
Very nice, thank you! :-)

I noticed that you have deleted some generated code, though. This means that once the editor GUI is opened in Projucer and saved, it will get re-added again automatically. So, to remove the label completely, you would need to open `PizLooperEditor.h` and `PizLooperEditor.cpp` in a Projucer project and delete the label there:
image

**Comment by loowps** [comment]
@sleiner Thanks and sry! I didn't know that the projucer could be used that way even when the project is built via cmake. Edit: I used the downloadable projucer of v7 and it's gui editor removed the part I expected. I reverted the version change and autoformatting and pushed another commit.

But tbh as the gui editor is deprecated I thought the metadata inside the cpp is simply legacy code that could be removed in a separate PR later on. I was under the impression that the JUCE-GUIs only could be made resizable (changing size while keeping the aspect ratio, not resizable the way it is now) when coded manually anyway.

**Review by sleiner — APPROVED** [review]

**Comment by sleiner** [comment]
@loowps 

> But tbh as the gui editor is deprecated I thought the metadata inside the cpp is simply legacy code that could be removed in a separate PR later on. I was under the impression that the JUCE-GUIs only could be made resizable (changing size while keeping the aspect ratio, not resizable the way it is now) when coded manually anyway.

There is definitely lots of room for improvement concerning these GUIs, so I am very much open to the idea of replacing the GUI editor stuff with more modern, "handcrafted" GUIs. Still, as is, (almost) all GUI stuff was built using the GUI editor in Projucer, so I would like to keep compatibility with it for the classes that we have. Since we currently get all the drawbacks of the GUI editor, we should at least get the benefits as well :-)

---

> I used the downloadable projucer of v7

FYI: Since this project pulls in JUCE, you can build the exact Projucer version matching this codebase quite easily:

1. Make sure that the `JUCE_BUILD_EXTRAS` variable in your CMake cache is set to `ON`. (Note that after changing `CMakeCache.txt`, you should re-run CMake to generate the new Makefiles accordingly).
2. Build the `Projucer` target.

**Comment by sleiner** [comment]
Anyway, thank you very much for putting in the effort ☺️ I will merge this later tonight 🚀

**Pull request merged**
